name: Setup Multi-Arch Build Environment
description: Set up QEMU emulation and Docker Buildx builder.
inputs:
  driver:
    description: 'Buildx driver (default docker-container)'
    required: false
    default: 'docker-container'
  login:
    description: 'Perform Docker registry login (true/false)'
    required: false
    default: 'false'
  registry:
    description: 'Registry server (default docker.io)'
    required: false
    default: 'docker.io'
  username:
    description: 'Registry username (required if login=true)'
    required: false
  password:
    description: 'Registry password or token (required if login=true)'
    required: false
runs:
  using: composite
  steps:
    - name: Set up QEMU (multi-arch emulation)
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: ${{ inputs.driver }}

    - name: Docker registry login
      if: inputs.login == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
