# Generated by Django 2.1.5 on 2019-01-14 11:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingPlaceFacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollingPlaceNoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
                ('stall_name', models.TextField()),
                ('stall_description', models.TextField()),
                ('stall_website', models.TextField()),
                ('stall_extra_info', models.TextField()),
                ('first_report', models.DateTimeField(auto_now_add=True)),
                ('latest_report', models.DateTimeField(auto_now=True)),
                ('chance_of_sausage', models.FloatField()),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollingPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.TextField()),
                ('premises', models.TextField()),
                ('address', models.TextField()),
                ('division', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('state', models.CharField(max_length=3)),
                ('wheelchair_access', models.TextField()),
                ('entrances_desc', models.TextField()),
                ('opening_hours', models.TextField()),
                ('booth_info', models.TextField()),
                ('facility_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaceFacilityType')),
                ('noms', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaceNoms')),
            ],
        ),
        migrations.AddIndex(
            model_name='pollingplacenoms',
            index=django.contrib.postgres.indexes.GinIndex(fields=['noms'], name='app_polling_noms_c0dc2d_gin'),
        ),
    ]
