# Generated by Django 2.1.7 on 2019-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingplaces',
            name='chance_of_sausage',
            field=models.FloatField(null=True),
        ),
    ]
