# Generated by Django 2.1.5 on 2019-01-27 06:00

import demsausage.app.enums
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190114_1113_squashed_0020_remove_stalls_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPollingPlaceNoms',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('noms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
                ('stall_name', models.TextField(blank=True)),
                ('stall_description', models.TextField(blank=True)),
                ('stall_website', models.TextField(blank=True)),
                ('stall_extra_info', models.TextField(blank=True)),
                ('first_report', models.DateTimeField(blank=True, editable=False, null=True)),
                ('latest_report', models.DateTimeField(blank=True, editable=False, null=True)),
                ('chance_of_sausage', models.FloatField(null=True)),
                ('source', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical polling place noms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPollingPlaces',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.TextField()),
                ('premises', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('division', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('state', models.CharField(max_length=8)),
                ('wheelchair_access', models.TextField(blank=True)),
                ('entrances_desc', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('booth_info', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('election', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Elections')),
                ('facility_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.PollingPlaceFacilityType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('noms', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.PollingPlaceNoms')),
            ],
            options={
                'verbose_name': 'historical polling places',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStalls',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('old_id', models.IntegerField()),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('noms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
                ('email', models.EmailField(max_length=254)),
                ('reported_timestamp', models.DateTimeField(blank=True, editable=False)),
                ('status', models.TextField(choices=[(demsausage.app.enums.StallStatus('Pending'), 'Pending'), (demsausage.app.enums.StallStatus('Approved'), 'Approved'), (demsausage.app.enums.StallStatus('Declined'), 'Declined')], default=demsausage.app.enums.StallStatus('Pending'))),
                ('mail_confirm_key', models.TextField(blank=True)),
                ('mail_confirmed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('election', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Elections')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('polling_place', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.PollingPlaces')),
            ],
            options={
                'verbose_name': 'historical stalls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
