# Generated by Django 2.1.5 on 2019-01-26 09:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190114_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('default_zoom_level', models.IntegerField()),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('polling_places_loaded', models.BooleanField(default=False)),
                ('election_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MailgunEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.TextField()),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
            ],
        ),
    ]
