# Generated by Django 2.1.7 on 2019-02-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pollingplaces_chance_of_sausage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingplacenoms',
            name='chance_of_sausage',
        ),
    ]
