# Generated by Django 2.1.5 on 2019-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_elections_mailgunevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='chance_of_sausage',
            field=models.FloatField(null=True),
        ),
    ]
