# Generated by Django 2.1.5 on 2019-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historicalpollingplacenoms_historicalpollingplaces_historicalstalls'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollingplaces',
            index=models.Index(fields=['election'], name='app_polling_electio_4cef11_idx'),
        ),
    ]
