# Generated by Django 2.1.5 on 2019-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190126_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='stall_extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='stall_website',
            field=models.TextField(blank=True),
        ),
    ]
