# Generated by Django 2.1.5 on 2019-01-27 06:26

import demsausage.app.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190127_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpollingplacenoms',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'required': ['bbq', 'cake', 'nothing', 'run_out'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='historicalstalls',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'required': ['bbq', 'cake', 'nothing', 'run_out'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'required': ['bbq', 'cake', 'nothing', 'run_out'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'required': ['bbq', 'cake', 'nothing', 'run_out'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
