# Generated by Django 2.1.7 on 2019-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190223_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstalls',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP address'),
        ),
    ]
