# Generated by Django 2.1.5 on 2019-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190127_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elections',
            name='short_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
