# Generated by Django 2.1.5 on 2019-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190126_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
