# Generated by Django 2.1.7 on 2019-04-03 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pollingplaceloaderevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingplaces',
            name='ec_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pollingplaces',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
