# Generated by Django 2.1.5 on 2019-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190126_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='first_report',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='latest_report',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
