# Generated by Django 2.1.5 on 2019-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190127_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstalls',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
