# Generated by Django 2.1.5 on 2019-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190126_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='stall_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='stall_name',
            field=models.TextField(blank=True),
        ),
    ]
