# Generated by Django 2.1.5 on 2019-01-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190127_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpollingplaces',
            old_name='entrances_desc',
            new_name='entrance_desc',
        ),
        migrations.RenameField(
            model_name='pollingplaces',
            old_name='entrances_desc',
            new_name='entrance_desc',
        ),
    ]
