# Generated by Django 2.1.5 on 2019-01-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190126_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingplaces',
            name='election',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.Elections'),
            preserve_default=False,
        ),
    ]
