# Generated by Django 2.1.5 on 2019-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pollingplaces_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='booth_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='entrances_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='wheelchair_access',
            field=models.TextField(blank=True),
        ),
    ]
