# Generated by Django 2.1.5 on 2019-01-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190127_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpollingplaces',
            old_name='division',
            new_name='divisions',
        ),
        migrations.RenameField(
            model_name='pollingplaces',
            old_name='division',
            new_name='divisions',
        ),
    ]
