# Generated by Django 2.2 on 2019-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_elections_geom2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='geom',
        ),
    ]
