# Generated by Django 2.2 on 2019-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_elections_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elections',
            old_name='geom2',
            new_name='geom',
        ),
    ]
