# Generated by Django 2.1.5 on 2019-01-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190126_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='noms',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaceNoms'),
        ),
    ]
