# Generated by Django 2.1.5 on 2019-01-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190126_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Elections'),
        ),
    ]
