# Generated by Django 2.2 on 2019-04-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190421_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='default_zoom_level',
        ),
    ]
