# Generated by Django 2.1.5 on 2019-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190128_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstalls',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='description',
            field=models.TextField(),
        ),
    ]
