# Generated by Django 2.1.5 on 2019-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190126_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='state',
            field=models.CharField(max_length=8),
        ),
    ]
