# Generated by Django 2.2 on 2019-04-22 01:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_elections_default_zoom_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
