# Generated by Django 2.2 on 2019-04-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190422_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pollingplacenoms',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stalls',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
    ]
