# Generated by Django 2.1.5 on 2019-01-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190126_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='facility_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaceFacilityType'),
        ),
    ]
