# Generated by Django 2.1.5 on 2019-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190126_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='premises',
            field=models.TextField(blank=True),
        ),
    ]
