# Generated by Django 2.1.5 on 2019-01-28 08:43

import demsausage.app.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190128_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='location_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'address': {'type': 'string'}, 'geom': {'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AddField(
            model_name='stalls',
            name='location_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'properties': {'address': {'type': 'string'}, 'geom': {'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
