# Generated by Django 2.1.5 on 2019-01-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190128_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalls',
            name='polling_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaces'),
        ),
    ]
