# Generated by Django 2.2 on 2019-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_pollingplaces_favourited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingplaces',
            name='favourited',
        ),
        migrations.AddField(
            model_name='pollingplacenoms',
            name='favourited',
            field=models.BooleanField(default=False),
        ),
    ]
