# Generated by Django 2.1.5 on 2019-01-27 05:05

import demsausage.app.enums
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190126_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('stall_name', models.TextField(blank=True)),
                ('stall_description', models.TextField(blank=True)),
                ('stall_website', models.TextField(blank=True)),
                ('stall_location_info', models.TextField(blank=True)),
                ('noms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
                ('email', models.EmailField(max_length=254)),
                ('reported_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[(demsausage.app.enums.StallStatus('Pending'), 'Pending'), (demsausage.app.enums.StallStatus('Approved'), 'Approved'), (demsausage.app.enums.StallStatus('Declined'), 'Declined')], default=demsausage.app.enums.StallStatus('Pending'))),
                ('mail_confirm_key', models.TextField(blank=True)),
                ('mail_confirmed', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Elections')),
                ('polling_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PollingPlaces')),
            ],
        ),
    ]
