# Generated by Django 2.1.5 on 2019-01-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stalls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalls',
            name='stall_location_info',
        ),
    ]
