# Generated by Django 2.1.5 on 2019-01-28 09:58

import demsausage.app.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190128_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpollingplacenoms',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='historicalstalls',
            name='location_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'address': {'type': 'string'}, 'geom': {'properties': {'coordinates': {'items': {'type': 'number'}, 'type': 'array'}, 'type': {'type': 'string'}}, 'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='historicalstalls',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='location_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'address': {'type': 'string'}, 'geom': {'properties': {'coordinates': {'items': {'type': 'number'}, 'type': 'array'}, 'type': {'type': 'string'}}, 'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='noms',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
