# Generated by Django 2.1.5 on 2019-01-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_stalls_stall_location_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stalls',
            old_name='stall_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='stalls',
            old_name='stall_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stalls',
            old_name='stall_website',
            new_name='website',
        ),
    ]
