# Generated by Django 2.2.1 on 2019-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_electoralboundaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralboundaries',
            name='loaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
