# Generated by Django 2.1.5 on 2019-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190128_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='short_name',
            field=models.TextField(unique=True),
        ),
    ]
