# Generated by Django 3.1.7 on 2021-04-04 05:51

import demsausage.app.models
import demsausage.app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190510_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralboundaries',
            name='election_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='electoralboundaries',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historicalstalls',
            name='location_info',
            field=models.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'address': {'type': 'string'}, 'geom': {'properties': {'coordinates': {'items': {'type': 'number'}, 'type': 'array'}, 'type': {'type': 'string'}}, 'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='historicalstalls',
            name='noms',
            field=models.JSONField(default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='mailgunevents',
            name='payload',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='pollingplaceloaderevents',
            name='payload',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='pollingplacenoms',
            name='noms',
            field=models.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='divisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.JSONField(blank=True, default=demsausage.app.models.default_profile_settings),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='location_info',
            field=models.JSONField(default=None, null=True, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'address': {'type': 'string'}, 'geom': {'properties': {'coordinates': {'items': {'type': 'number'}, 'type': 'array'}, 'type': {'type': 'string'}}, 'type': 'object'}, 'name': {'type': 'string'}, 'state': {'type': 'string'}}, 'required': ['name', 'address', 'state', 'geom'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='noms',
            field=models.JSONField(default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
