# Generated by Django 2.1.5 on 2019-01-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190127_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalls',
            name='is_active',
        ),
    ]
