# Generated by Django 2.1.5 on 2019-02-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190129_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpollingplacenoms',
            old_name='stall_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicalpollingplacenoms',
            old_name='stall_extra_info',
            new_name='extra_info',
        ),
        migrations.RenameField(
            model_name='historicalpollingplacenoms',
            old_name='stall_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalpollingplacenoms',
            old_name='stall_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='pollingplacenoms',
            old_name='stall_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pollingplacenoms',
            old_name='stall_extra_info',
            new_name='extra_info',
        ),
        migrations.RenameField(
            model_name='pollingplacenoms',
            old_name='stall_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pollingplacenoms',
            old_name='stall_website',
            new_name='website',
        ),
    ]
