# Generated by Django 3.2.12 on 2022-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210404_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralboundaries',
            name='division_name',
            field=models.TextField(),
        ),
    ]
