# Generated by Django 2.1.5 on 2019-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190206_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpollingplaces',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingplaces',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
