# Generated by Django 3.2.13 on 2022-05-01 09:33

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_electoralboundaries_division_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField()),
                ('job_name', models.TextField()),
                ('job_func_name', models.TextField()),
                ('queue', models.TextField()),
                ('worker', models.TextField()),
                ('status', models.TextField(choices=[(demsausage.app.enums.TaskStatus['SUCCESS'], 'Success'), (demsausage.app.enums.TaskStatus['FAILED'], 'Failed')])),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('meta', models.JSONField(blank=True, default=None, null=True)),
                ('job_args', models.JSONField(blank=True, default=None, null=True)),
                ('job_kwargs', models.JSONField(blank=True, default=None, null=True)),
                ('date_enqueued', models.DateTimeField()),
                ('date_done', models.DateTimeField()),
            ],
        ),
    ]
