# Generated by Django 2.1.5 on 2019-02-10 09:06

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190209_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpollingplaces',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='pollingplaces',
            name='draft',
        ),
        migrations.AddField(
            model_name='historicalpollingplaces',
            name='status',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceStatus('Archived'), 'Archived'), (demsausage.app.enums.PollingPlaceStatus('Active'), 'Active'), (demsausage.app.enums.PollingPlaceStatus('Draft'), 'Draft')], default=demsausage.app.enums.PollingPlaceStatus('Draft')),
        ),
        migrations.AddField(
            model_name='pollingplaces',
            name='status',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceStatus('Archived'), 'Archived'), (demsausage.app.enums.PollingPlaceStatus('Active'), 'Active'), (demsausage.app.enums.PollingPlaceStatus('Draft'), 'Draft')], default=demsausage.app.enums.PollingPlaceStatus('Draft')),
        ),
    ]
