# Generated by Django 2.1.5 on 2019-02-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190210_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpollingplacenoms',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpollingplaces',
            name='election',
        ),
        migrations.RemoveField(
            model_name='historicalpollingplaces',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='historicalpollingplaces',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpollingplaces',
            name='noms',
        ),
        migrations.DeleteModel(
            name='HistoricalPollingPlaceNoms',
        ),
        migrations.DeleteModel(
            name='HistoricalPollingPlaces',
        ),
    ]
