# Generated by Django 4.2.5 on 2023-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_historicalstalls_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='is_federal',
            field=models.BooleanField(null=True),
        ),
    ]
