# Generated by Django 4.2.5 on 2023-10-16 05:51

from django.db import migrations, models


def set_field_values(apps, schema_editor):
    for election in apps.get_model("app", "Elections").objects.filter(id__in=[1, 9, 27, 37, 53]):
        election.is_federal = True
        election.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_elections_is_federal'),
    ]

    operations = [
        migrations.RunPython(set_field_values),
        migrations.AlterField(
            model_name='elections',
            name='is_federal',
            field=models.BooleanField(default=False),
        ),
    ]
