# Generated by Django 4.2.5 on 2024-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_elections_is_federal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingplaces',
            name='wheelchair_access_description',
            field=models.TextField(blank=True),
        ),
    ]
