# Generated by Django 4.2.5 on 2024-06-12 11:42

import demsausage.app.enums

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_pollingplaces_wheelchair_access_description'),
    ]

    def clean_wheelchair_access_data(apps, schema_editor):
        cursor = connection.cursor()

        queries = [
            # Election 36 (New South Wales Local Government Elections 2021)
            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted', wheelchair_access_description = REGEXP_REPLACE(wheelchair_access, '^Assisted access, ', '') WHERE election_id = 36 AND status = 'Active' AND STARTS_WITH(wheelchair_access, 'Assisted access, ') is TRUE;",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted' WHERE election_id = 36 AND status = 'Active' AND wheelchair_access IN ('Assisted wheelchair access', 'disabled parking: NO; wheelchair access: NO; wheelchair assisted: YES');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full', wheelchair_access_description = wheelchair_access WHERE election_id = 36 AND status = 'Active' AND wheelchair_access IN ('disabled parking: NO; wheelchair access: YES; wheelchair assisted: NO', 'disabled parking: YES; wheelchair access: YES; wheelchair assisted: NO', 'disabled parking: YES; wheelchair access: YES; wheelchair assisted: YES');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full' WHERE election_id = 36 AND status = 'Active' AND wheelchair_access IN ('Fully wheelchair accessible', 'Full wheelchair access');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'None' WHERE election_id = 36 AND status = 'Active' AND wheelchair_access IN ('disabled parking: NO; wheelchair access: NO; wheelchair assisted: NO', 'Not Wheelchair Accessible');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'None', wheelchair_access_description = wheelchair_access WHERE election_id = 36 AND status = 'Active' AND wheelchair_access IN ('disabled parking: YES; wheelchair access: NO; wheelchair assisted: NO');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Unknown' WHERE election_id = 36 AND status = 'Active' AND wheelchair_access = '';",

            # Election 35 (New South Wales Election 2023)
            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted', wheelchair_access_description = REGEXP_REPLACE(wheelchair_access, '^Wheelchair accessible with assistance: ', '') WHERE election_id = 35 AND status = 'Active' AND STARTS_WITH(wheelchair_access, 'Wheelchair accessible with assistance: ') is TRUE;",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full' WHERE election_id = 35 AND status = 'Active' AND wheelchair_access IN ('Wheelchair accessible');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Unknown' WHERE election_id = 35 AND status = 'Active' AND wheelchair_access = '';",

            # Election 26 (New South Wales Election 2019)
            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted', wheelchair_access_description = REGEXP_REPLACE(wheelchair_access, '^Wheelchair accessible with assistance: ', '') WHERE election_id = 26 AND status = 'Active' AND STARTS_WITH(wheelchair_access, 'Wheelchair accessible with assistance: ') is TRUE;",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full' WHERE election_id = 26 AND status = 'Active' AND wheelchair_access IN ('Wheelchair accessible');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Unknown' WHERE election_id = 26 AND status = 'Active' AND wheelchair_access = '';",

            # Migrate the remaining descriptions that are almost there and can be easily mapped to our allowed values
            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted' WHERE status = 'Active' AND wheelchair_access IN ('Assisted wheelchair access', 'With Assistance', 'Assisted Access', 'Assistance', 'Wheelchair Access', 'Wheelchair accessible');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full' WHERE status = 'Active' AND wheelchair_access IN ('Full Access', 'Full wheelchair access', 'Fully wheelchair accessible', 'Independent wheelchair access');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'None' WHERE status = 'Active' AND wheelchair_access IN ('No Access', 'No wheelchair access', 'Limited to no wheelchair access');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Unknown' WHERE status = 'Active' AND wheelchair_access IN ('');",

            # Older elections using booth_info
            # This is by no means exhaustive, but it's good enough for these old elections
            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Assisted', booth_info = '' WHERE status = 'Active' AND wheelchair_access = 'Unknown' AND booth_info IN ('assisted wheelchair access', ' ;  Assisted Wheelchair Access', 'Assisted Disabled', 'Assisted access', 'Hall, assisted wheelchair access');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'Full', booth_info = '' WHERE status = 'Active' AND wheelchair_access = 'Unknown' AND booth_info IN ('full wheelchair access', ' ;  Full Wheelchair Access');",

            "UPDATE demsausage.app_pollingplaces SET wheelchair_access = 'None', booth_info = '' WHERE status = 'Active' AND wheelchair_access = 'Unknown' AND booth_info IN ('no wheelchair access');"
        ]

        for query in queries:
            cursor.execute(query)


    operations = [
        migrations.RunPython(clean_wheelchair_access_data),
        migrations.AlterField(
            model_name='pollingplaces',
            name='wheelchair_access',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceWheelchairAccess['NONE'], 'None'), (demsausage.app.enums.PollingPlaceWheelchairAccess['ASSISTED'], 'Assisted'), (demsausage.app.enums.PollingPlaceWheelchairAccess['FULL'], 'Full'), (demsausage.app.enums.PollingPlaceWheelchairAccess['UNKNOWN'], 'Unknown')], default=demsausage.app.enums.PollingPlaceStatus['DRAFT']),
        ),
    ]
