# Generated by Django 4.2.5 on 2024-06-13 11:20

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_pollingplaces_wheelchair_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplaces',
            name='wheelchair_access',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceWheelchairAccess['NONE'], 'None'), (demsausage.app.enums.PollingPlaceWheelchairAccess['ASSISTED'], 'Assisted'), (demsausage.app.enums.PollingPlaceWheelchairAccess['FULL'], 'Full'), (demsausage.app.enums.PollingPlaceWheelchairAccess['UNKNOWN'], 'Unknown')]),
        ),
    ]
