# Generated by Django 4.2.13 on 2024-07-10 14:07

import demsausage.app.enums

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_pollingplaces_wheelchair_access'),
    ]

    def populate_jurisdictions(apps, schema_editor):
        cursor = connection.cursor()

        queries = [
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 55;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 54;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'aus' WHERE id = 53;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 52;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 51;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 50;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 49;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 48;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 47;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'tas' WHERE id = 46;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 45;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 44;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 43;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 42;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'act' WHERE id = 41;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'act' WHERE id = 40;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nt' WHERE id = 39;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nt' WHERE id = 38;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'aus' WHERE id = 37;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 36;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 35;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 34;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 33;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 32;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 31;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'act' WHERE id = 30;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nt' WHERE id = 29;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'tas' WHERE id = 28;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'aus' WHERE id = 27;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 26;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 25;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 24;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 23;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 22;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'tas' WHERE id = 21;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 20;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 19;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 18;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 17;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 16;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'tas' WHERE id = 15;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 14;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 13;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 12;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nt' WHERE id = 11;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'act' WHERE id = 10;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'aus' WHERE id = 9;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 8;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'nsw' WHERE id = 7;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'qld' WHERE id = 6;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'vic' WHERE id = 5;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'wa' WHERE id = 4;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'sa' WHERE id = 3;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'tas' WHERE id = 2;",
            "UPDATE demsausage.app_elections SET jurisdiction = 'aus' WHERE id = 1;",
        ]

        for query in queries:
            cursor.execute(query)

    operations = [
        migrations.AddField(
            model_name='elections',
            name='jurisdiction',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceJurisdiction['WA'], 'wa'), (demsausage.app.enums.PollingPlaceJurisdiction['SA'], 'sa'), (demsausage.app.enums.PollingPlaceJurisdiction['NSW'], 'nsw'), (demsausage.app.enums.PollingPlaceJurisdiction['ACT'], 'act'), (demsausage.app.enums.PollingPlaceJurisdiction['VIC'], 'vic'), (demsausage.app.enums.PollingPlaceJurisdiction['NT'], 'nt'), (demsausage.app.enums.PollingPlaceJurisdiction['TAS'], 'tas'), (demsausage.app.enums.PollingPlaceJurisdiction['QLD'], 'qld'), (demsausage.app.enums.PollingPlaceJurisdiction['AUS'], 'aus')], default='', blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_jurisdictions),
        migrations.AlterField(
            model_name='elections',
            name='jurisdiction',
            field=models.TextField(choices=[(demsausage.app.enums.PollingPlaceJurisdiction['WA'], 'wa'), (demsausage.app.enums.PollingPlaceJurisdiction['SA'], 'sa'), (demsausage.app.enums.PollingPlaceJurisdiction['NSW'], 'nsw'), (demsausage.app.enums.PollingPlaceJurisdiction['ACT'], 'act'), (demsausage.app.enums.PollingPlaceJurisdiction['VIC'], 'vic'), (demsausage.app.enums.PollingPlaceJurisdiction['NT'], 'nt'), (demsausage.app.enums.PollingPlaceJurisdiction['TAS'], 'tas'), (demsausage.app.enums.PollingPlaceJurisdiction['QLD'], 'qld'), (demsausage.app.enums.PollingPlaceJurisdiction['AUS'], 'aus')]),
        ),
    ]
