# Generated by Django 4.2.13 on 2024-07-12 06:54

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_elections_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='submitter_type',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallSubmitterType['OWNER'], 'owner'), (demsausage.app.enums.StallSubmitterType['TIPOFF'], 'tipoff')]),
        ),
        migrations.AddField(
            model_name='stalls',
            name='submitter_type',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallSubmitterType['OWNER'], 'owner'), (demsausage.app.enums.StallSubmitterType['TIPOFF'], 'tipoff')]),
        ),
    ]
