# Generated by Django 4.2.13 on 2024-07-18 14:00

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_historicalstalls_submitter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralboundaries',
            name='state',
            field=models.CharField(choices=[(demsausage.app.enums.PollingPlaceState['NSW'], 'NSW'), (demsausage.app.enums.PollingPlaceState['VIC'], 'VIC'), (demsausage.app.enums.PollingPlaceState['QLD'], 'QLD'), (demsausage.app.enums.PollingPlaceState['WA'], 'WA'), (demsausage.app.enums.PollingPlaceState['SA'], 'SA'), (demsausage.app.enums.PollingPlaceState['TAS'], 'TAS'), (demsausage.app.enums.PollingPlaceState['ACT'], 'ACT'), (demsausage.app.enums.PollingPlaceState['NT'], 'NT'), (demsausage.app.enums.PollingPlaceState['Overseas'], 'Overseas')]),
        ),
        migrations.AlterField(
            model_name='pollingplaces',
            name='state',
            field=models.CharField(choices=[(demsausage.app.enums.PollingPlaceState['NSW'], 'NSW'), (demsausage.app.enums.PollingPlaceState['VIC'], 'VIC'), (demsausage.app.enums.PollingPlaceState['QLD'], 'QLD'), (demsausage.app.enums.PollingPlaceState['WA'], 'WA'), (demsausage.app.enums.PollingPlaceState['SA'], 'SA'), (demsausage.app.enums.PollingPlaceState['TAS'], 'TAS'), (demsausage.app.enums.PollingPlaceState['ACT'], 'ACT'), (demsausage.app.enums.PollingPlaceState['NT'], 'NT'), (demsausage.app.enums.PollingPlaceState['Overseas'], 'Overseas')]),
        ),
    ]
