# Generated by Django 4.2.13 on 2024-08-09 07:29

import demsausage.app.enums

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_electoralboundaries_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='tipoff_source',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallTipOffSource['In_Person'], 'in-person'), (demsausage.app.enums.StallTipOffSource['Online'], 'online'), (demsausage.app.enums.StallTipOffSource['Newsletter'], 'newsletter'), (demsausage.app.enums.StallTipOffSource['Other'], 'other')]),
        ),
        migrations.AddField(
            model_name='stalls',
            name='tipoff_source',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallTipOffSource['In_Person'], 'in-person'), (demsausage.app.enums.StallTipOffSource['Online'], 'online'), (demsausage.app.enums.StallTipOffSource['Newsletter'], 'newsletter'), (demsausage.app.enums.StallTipOffSource['Other'], 'other')]),
        ),
    ]
