# Generated by Django 4.2.13 on 2024-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_historicalstalls_tipoff_source_stalls_tipoff_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='tipoff_source_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stalls',
            name='tipoff_source_other',
            field=models.TextField(blank=True),
        ),
    ]
