# Generated by Django 4.2.13 on 2024-09-13 13:05

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_historicalstalls_tipoff_source_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstalls',
            name='submitter_type',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallSubmitterType['OWNER'], 'owner'), (demsausage.app.enums.StallSubmitterType['TIPOFF'], 'tipoff'), (demsausage.app.enums.StallSubmitterType['TIPOFF_RUN_OUT'], 'tipoff_run_out'), (demsausage.app.enums.StallSubmitterType['TIPOFF_RED_CROSS_OF_SHAME'], 'tipoff_red_cross_of_shame')]),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='submitter_type',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.StallSubmitterType['OWNER'], 'owner'), (demsausage.app.enums.StallSubmitterType['TIPOFF'], 'tipoff'), (demsausage.app.enums.StallSubmitterType['TIPOFF_RUN_OUT'], 'tipoff_run_out'), (demsausage.app.enums.StallSubmitterType['TIPOFF_RED_CROSS_OF_SHAME'], 'tipoff_red_cross_of_shame')]),
        ),
    ]
