# Generated by Django 4.2.13 on 2024-11-19 23:25

import demsausage.app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0036_alter_historicalstalls_submitter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPollingPlaceNoms',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('noms', models.JSONField(blank=True, default=None, validators=[demsausage.app.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'bacon_and_eggs': {'type': 'boolean'}, 'bbq': {'type': 'boolean'}, 'cake': {'type': 'boolean'}, 'coffee': {'type': 'boolean'}, 'free_text': {'type': 'string'}, 'halal': {'type': 'boolean'}, 'nothing': {'type': 'boolean'}, 'run_out': {'type': 'boolean'}, 'vego': {'type': 'boolean'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})])),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('favourited', models.BooleanField(default=False)),
                ('website', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('first_report', models.DateTimeField(blank=True, editable=False, null=True)),
                ('latest_report', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical polling place noms',
                'verbose_name_plural': 'historical polling place nomss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
