# Generated by Django 4.2.13 on 2024-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_historicalpollingplacenoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpollingplacenoms',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingplacenoms',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
