# Generated by Django 4.2.19 on 2025-02-09 11:02

import demsausage.app.enums

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_historicalpollingplacenoms_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstalls",
            name="previous_status",
            field=models.TextField(
                choices=[
                    (demsausage.app.enums.StallStatus["PENDING"], "Pending"),
                    (demsausage.app.enums.StallStatus["APPROVED"], "Approved"),
                    (demsausage.app.enums.StallStatus["DECLINED"], "Declined"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stalls",
            name="previous_status",
            field=models.TextField(
                choices=[
                    (demsausage.app.enums.StallStatus["PENDING"], "Pending"),
                    (demsausage.app.enums.StallStatus["APPROVED"], "Approved"),
                    (demsausage.app.enums.StallStatus["DECLINED"], "Declined"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
