# Generated by Django 4.2.19 on 2025-02-09 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_historicalstalls_previous_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstalls',
            old_name='approved_on',
            new_name='triaged_on',
        ),
        migrations.RenameField(
            model_name='stalls',
            old_name='approved_on',
            new_name='triaged_on',
        ),
        migrations.AddField(
            model_name='historicalstalls',
            name='triaged_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stalls',
            name='triaged_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
