# Generated by Django 4.2.19 on 2025-02-09 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0040_rename_approved_on_historicalstalls_triaged_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalls',
            name='triaged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
