# Generated by Django 4.2.19 on 2025-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_stalls_triaged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstalls',
            name='owner_edit_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stalls',
            name='owner_edit_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
