# Generated by Django 4.2.19 on 2025-03-09 01:43

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_historicalstalls_owner_edit_timestamp_and_more"),
    ]

    def fill_historical_data(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            "UPDATE demsausage.app_elections SET is_state = true WHERE id IN (51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 35, 34, 33, 32, 31, 30, 29, 28, 26, 25, 16, 15, 13, 12, 11, 10, 7, 6, 5, 3, 2);"
        )

    operations = [
        migrations.AddField(
            model_name="elections",
            name="is_state",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fill_historical_data),
    ]
