# Generated by Django 4.2.19 on 2025-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_elections_is_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpollingplacenoms',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pollingplacenoms',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
