# Generated by Django 4.2.19 on 2025-03-23 11:01

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_historicalpollingplacenoms_internal_notes_and_more"),
    ]

    def backfill_true(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            "UPDATE demsausage.app_elections SET analytics_stats_saved = true;"
        )

    operations = [
        migrations.AddField(
            model_name="elections",
            name="analytics_stats_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_true),
    ]
