# Generated by Django 4.2.19 on 2025-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_elections_analytics_stats_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='analytics_stats_saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
