# Generated by Django 4.2.19 on 2025-03-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_elections_analytics_stats_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='analytics_stats_saved',
        ),
    ]
