# Generated by Django 4.2.19 on 2025-03-23 11:06

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_elections_analytics_stats_saved"),
    ]

    def backfill_null(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            "UPDATE demsausage.app_elections SET analytics_stats_saved = NULL;"
        )

    operations = [
        migrations.AddField(
            model_name="elections",
            name="analytics_stats_saved",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RunPython(backfill_null),
    ]
