# Generated by Django 4.2.19 on 2025-03-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_elections_analytics_stats_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
