# Generated by Django 4.2.19 on 2025-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_elections_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingplaces',
            name='chance_of_sausage_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
