# Generated by Django 4.2.20 on 2025-04-09 22:24

import demsausage.app.enums

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_historicalmetapollingplacestasks_outcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmetapollingplacestasks",
            name="outcome",
            field=models.TextField(
                choices=[
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["COMPLETED"],
                        "Completed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["CLOSED"],
                        "Closed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["DEFERRED"],
                        "Deferred",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metapollingplacestasks",
            name="outcome",
            field=models.TextField(
                choices=[
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["COMPLETED"],
                        "Completed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["CLOSED"],
                        "Closed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["DEFERRED"],
                        "Deferred",
                    ),
                ],
                null=True,
            ),
        ),
    ]
