# Generated by Django 4.2.20 on 2025-04-09 22:27

import demsausage.app.enums

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_alter_historicalmetapollingplacestasks_outcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmetapollingplacestasks",
            name="outcome",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["COMPLETED"],
                        "Completed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["CLOSED"],
                        "Closed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["DEFERRED"],
                        "Deferred",
                    ),
                ],
                default="",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metapollingplacestasks",
            name="outcome",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["COMPLETED"],
                        "Completed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["CLOSED"],
                        "Closed",
                    ),
                    (
                        demsausage.app.enums.MetaPollingPlaceTaskOutcome["DEFERRED"],
                        "Deferred",
                    ),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
