# Generated by Django 4.2.20 on 2025-04-10 12:10

import demsausage.app.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_historicalmetapollingplacestasks_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetapollingplacesremarks',
            name='meta_polling_place_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.metapollingplacestasks'),
        ),
        migrations.AddField(
            model_name='metapollingplacesremarks',
            name='meta_polling_place_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.metapollingplacestasks'),
        ),
        migrations.AlterField(
            model_name='historicalmetapollingplacestasks',
            name='outcome',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.MetaPollingPlaceTaskOutcome['COMPLETED'], 'Completed'), (demsausage.app.enums.MetaPollingPlaceTaskOutcome['DEFERRED'], 'Deferred'), (demsausage.app.enums.MetaPollingPlaceTaskOutcome['CLOSED'], 'Closed')]),
        ),
        migrations.AlterField(
            model_name='metapollingplacestasks',
            name='outcome',
            field=models.TextField(blank=True, choices=[(demsausage.app.enums.MetaPollingPlaceTaskOutcome['COMPLETED'], 'Completed'), (demsausage.app.enums.MetaPollingPlaceTaskOutcome['DEFERRED'], 'Deferred'), (demsausage.app.enums.MetaPollingPlaceTaskOutcome['CLOSED'], 'Closed')]),
        ),
    ]
