# Generated by Django 4.2.20 on 2025-04-10 22:23

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_historicalmetapollingplacesremarks_meta_polling_place_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetapollingplaceslinks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceLinkType['OFFICIAL'], 'Official Website'), (demsausage.app.enums.MetaPollingPlaceLinkType['FACEBOOK'], 'Facebook'), (demsausage.app.enums.MetaPollingPlaceLinkType['OTHER'], 'Other')]),
        ),
        migrations.AlterField(
            model_name='metapollingplaceslinks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceLinkType['OFFICIAL'], 'Official Website'), (demsausage.app.enums.MetaPollingPlaceLinkType['FACEBOOK'], 'Facebook'), (demsausage.app.enums.MetaPollingPlaceLinkType['OTHER'], 'Other')]),
        ),
    ]
