# Generated by Django 4.2.20 on 2025-04-10 23:17

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_historicalmetapollingplaceslinks_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetapollingplacestasks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceTaskType['REVIEW_DRAFT'], 'Review Draft'), (demsausage.app.enums.MetaPollingPlaceTaskType['QA_PP_MISMATCH'], 'Polling Place Mismatch'), (demsausage.app.enums.MetaPollingPlaceTaskType['CROWDSOURCE_FROM_FACEBOOK'], 'Crowdsource from Facebook')]),
        ),
        migrations.AlterField(
            model_name='metapollingplacestasks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceTaskType['REVIEW_DRAFT'], 'Review Draft'), (demsausage.app.enums.MetaPollingPlaceTaskType['QA_PP_MISMATCH'], 'Polling Place Mismatch'), (demsausage.app.enums.MetaPollingPlaceTaskType['CROWDSOURCE_FROM_FACEBOOK'], 'Crowdsource from Facebook')]),
        ),
    ]
