# Generated by Django 4.2.20 on 2025-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_historicalmetapollingplacestasks_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpollingplacenoms',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='pollingplacenoms',
            name='internal_notes',
        ),
        migrations.AddField(
            model_name='pollingplaces',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
