# Generated by Django 4.2.20 on 2025-04-27 05:20

import demsausage.app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_remove_historicalpollingplacenoms_internal_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetapollingplaceslinks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceLinkType['OFFICIAL'], 'Official Website'), (demsausage.app.enums.MetaPollingPlaceLinkType['FACEBOOK'], 'Facebook'), (demsausage.app.enums.MetaPollingPlaceLinkType['P_AND_C'], 'P&C'), (demsausage.app.enums.MetaPollingPlaceLinkType['NEWSLETTER'], 'Newsletter'), (demsausage.app.enums.MetaPollingPlaceLinkType['OTHER'], 'Other')]),
        ),
        migrations.AlterField(
            model_name='metapollingplaceslinks',
            name='type',
            field=models.TextField(choices=[(demsausage.app.enums.MetaPollingPlaceLinkType['OFFICIAL'], 'Official Website'), (demsausage.app.enums.MetaPollingPlaceLinkType['FACEBOOK'], 'Facebook'), (demsausage.app.enums.MetaPollingPlaceLinkType['P_AND_C'], 'P&C'), (demsausage.app.enums.MetaPollingPlaceLinkType['NEWSLETTER'], 'Newsletter'), (demsausage.app.enums.MetaPollingPlaceLinkType['OTHER'], 'Other')]),
        ),
    ]
