services:
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      - ./logs/django:/app/logs:delegated
    environment:
      - BUILD=YES
    env_file:
      - ./secrets/staging/sausage-web.staging.env
      - ./secrets/dev/sausage-web-db.dev.env
  public_redesign:
    image: node:20-alpine3.19
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./public-redesign:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/staging/sausage-public-redesign-frontend.staging.env
  admin_redesign:
    image: node:20-alpine3.19
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./admin-redesign:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/staging/sausage-admin-redesign-frontend.staging.env
