version: "3.8"
services:
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    # command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      # - ./secrets/:/secrets:delegated
    # ports:
    #   - "8000:8000"
    env_file:
      - ./sausage-web.prod-local.env
      - ./sausage-db.dev.env
