version: "3.8"
services:
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      - ./logs/django:/app/logs:delegated
    environment:
      - BUILD=YES
    env_file:
      - ./secrets/sausage-web.prod-local.env
      - ./secrets/sausage-web-db.dev.env
