services:
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      - ./logs/django:/app/logs:delegated
    environment:
      - BUILD=YES
    env_file:
      - ./secrets/prod/sausage-web.production.env
      - ./secrets/dev/sausage-web-db.dev.env
  public:
    image: node:20-alpine3.19
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./public:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/prod/sausage-public-frontend.production.env
  public_redesign:
    image: node:20-alpine3.19
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./public-redesign:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/prod/sausage-public-redesign-frontend.production.env
  admin:
    image: node:20-alpine3.19
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./admin:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/prod/sausage-admin-frontend.production.env
