version: "3.8"
services:
  django:
    build: django/
    entrypoint: /app/foo.sh
    # command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      # - ./secrets/:/secrets:delegated
    # ports:
    #   - "8000:8000"
    environment:
      - FOO=BAR
      - BUILD=YES
    # env_file:
    #   - ./secrets/sausage-web.prod-local.env
    #   - ./secrets/sausage-web-db.dev.env
