version: "3.7"
services:
  frontend_public:
    image: node:11.11.0-alpine
    command: build
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./public:/app:delegated
      - ./build:/build:delegated
    env_file:
      - secrets/sausage-public-frontend.prod-local.env
  frontend_admin:
    image: node:11.11.0-alpine
    command: build
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./admin:/app:delegated
      - ./build:/build:delegated
    env_file:
      - secrets/sausage-admin-frontend.prod-local.env
