[tool.poetry]
name = "demsausage"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.2.9"
psycopg2-binary = "^2.9.9"
djangorestframework = "^3.14.0"
django-cors-headers = "^4.3.1"
django-model-utils = "^4.3.1"
googlemaps = "^4.10.0"
gunicorn = "^20.1.0"
gevent = "^22.10.1"
greenlet = "^1.1.3"
social-auth-app-django = "^5.4.0"
social-auth-core = "^4.5.1"
sentry-sdk = "^1.39.2"
django-simple-history = "^3.4.0"
jsonschema = "^4.21.1"
django-pymemcache = "^1.0.0"
djangorestframework-gis = "^1.0"
django-filter = "23.5"
djangorestframework-csv = "^3.0.2"
requests = "^2.31.0"
chardet = "^5.2.0"
drf-spectacular = "^0.27.1"
selenium = "^4.16.0"
webdriver-manager = "^4.0.1"
pytz = "^2023.3"
rq = "^1.15.1"
django-rq = "^2.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"