[tool.poetry]
name = "demsausage"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.2"
psycopg2-binary = "^2.9.1"
djangorestframework = "^3.12.4"
django-cors-headers = "^3.8.0"
django-model-utils = "^4.1.1"
googlemaps = "^4.5.3"
gunicorn = "^20.1.0"
gevent = "^21.8.0"
greenlet = "^1.1.1"
social-auth-app-django = "^5.0.0"
social-auth-core = "^4.1.0"
sentry-sdk = "^1.4.3"
django-simple-history = "^3.0.0"
jsonschema = "^3.2.0"
django-pymemcache = "^1.0.0"
djangorestframework-gis = "^0.17"
django-filter = "^21.1"
djangorestframework-csv = "^2.1.1"
requests = "^2.26.0"
chardet = "^4.0.0"
drf-spectacular = "^0.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
