[tool.poetry]
name = "demsausage"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1.5"
psycopg2-binary = "^2.9.8"
djangorestframework = "^3.14.0"
django-cors-headers = "^3.13.0"
django-model-utils = "^4.3.1"
googlemaps = "^4.7.3"
gunicorn = "^20.1.0"
gevent = "^22.10.1"
greenlet = "^1.1.3"
social-auth-app-django = "^5.1.0"
social-auth-core = "^4.3.0"
sentry-sdk = "^1.31.0"
django-simple-history = "^3.2.0"
jsonschema = "^4.17.3"
django-pymemcache = "^1.0.0"
djangorestframework-gis = "^1.0"
django-filter = "21.1"
djangorestframework-csv = "^2.1.1"
requests = "^2.31.0"
chardet = "^5.1.0"
drf-spectacular = "^0.26.5"
selenium = "^4.12.0"
webdriver-manager = "^3.8.5"
pytz = "^2023.3"
rq = "^1.15.1"
django-rq = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"