[tool.poetry]
name = "demsausage"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "4.0.5"
psycopg2-binary = "^2.9.3"
djangorestframework = "^3.13.1"
django-cors-headers = "^3.12.0"
django-model-utils = "^4.2.0"
googlemaps = "^4.6.0"
gunicorn = "^20.1.0"
gevent = "^21.12.0"
greenlet = "^1.1.2"
social-auth-app-django = "^5.0.0"
social-auth-core = "^4.2.0"
sentry-sdk = "^1.5.12"
django-simple-history = "^3.1.1"
jsonschema = "^4.6.0"
django-pymemcache = "^1.0.0"
djangorestframework-gis = "^0.18"
django-filter = "^21.1"
djangorestframework-csv = "^2.1.1"
requests = "^2.27.1"
chardet = "^4.0.0"
drf-spectacular = "^0.22.1"
selenium = "^4.2.0"
webdriver-manager = "^3.7.0"
pytz = "^2022.1"
rq = "^1.10.1"
django-rq = "^2.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
