// This must be the first line in src/index.js
// https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill
import 'classlist-polyfill'
// Import any specific polyfills required for legacy browsers
import 'core-js/modules/es.array.find'
import 'core-js/modules/es.array.find-index'
import 'core-js/modules/es.array.includes'
import 'core-js/modules/es.array.is-array'
import 'core-js/modules/es.function.name'
import 'core-js/modules/es.math.sign'
import 'core-js/modules/es.math.trunc'
import 'core-js/modules/es.number.is-nan'
import 'core-js/modules/es.object.entries'
import 'core-js/modules/es.object.is-frozen'
import 'core-js/modules/es.object.keys'
import 'core-js/modules/es.object.values'
import 'core-js/modules/es.string.includes'
import 'core-js/modules/es.string.starts-with'
import 'raf/polyfill'
import 'react-app-polyfill/ie11'
